### ISSUE TITLE
Invalid feedback is invisible

### ISSUE THREAD

**Issue by esl51** [kartik-v/yii2-widget-typeahead#43]
Invalid feedback is invisible because there is no input with `is-invalid` class near it.
Initialization:

```php
echo $form->field($model, 'autocomplete')->widget(Typeahead::class, [
    'dataset' => [[
        'remote' => [
            'url' => Url::toRoute(['site/autocomplete']) . '?term=%QUERY',
            'wildcard' => '%QUERY'
        ],
        'display' => 'value',
        'limit' => 10,
    ]],
]);
```

With ajax validation on blur I have the following markup:

```html
<div class="form-group required validating">
  <label for="...">Label</label>
  <div>
    <span class="twitter-typeahead" style="...">
      <input type="text" class="form-control tt-hint" ...>
      <input id="..." type="text" class="form-control tt-input is-invalid" ...>
    </span>
    ...
  </div>
  <div class="invalid-feedback">The field is required.</div>
</div>
```

Bootstrap 4 rules:

```css
.invalid-feedback {
  display: none;
}
.was-validated :invalid ~ .invalid-feedback,
.was-validated :invalid ~ .invalid-tooltip,
.is-invalid ~ .invalid-feedback,
.is-invalid ~ .invalid-tooltip {
  display: block;
}
```
